@echo off
title Restarting Anti Gravity Server...
cd /d "%~dp0"
echo Stopping old server...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3005" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul
timeout /t 2 /nobreak >nul
echo Installing dependencies...
call npm install --silent
echo.
echo Starting server...
node server-fixed.js
